name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - ipympl
  - jsonschema >=4.8
  - lz4 >= 4.3.0
  - numpy >= 1.26
  - matplotlib
  - packaging
  - pandas >= 2.0.0
  - photutils >=2.3.0
  - pip
  - pyarrow >= 10.0.1
  - python == 3.14
  - pyyaml >= 6.0
  - requests >=2.26
  - scipy >=1.14.1
  - pip:
      - asdf_standard >=1.1.0
      - asdf >= 4.1.0,<6
      - asdf-astropy >=0.8.0
      - astropy >= 6.0
      - crds >=13.0.2
      - drizzle >= 2.2,<2.3.0
      - gwcs >= 1.0.1,<2
      - stcal >= 1.18.0,<2
      - stpipe >=0.11.0,<2
      - roman_datamodels >=1.0
      - romancal >= 1.0
      - romanisim >= 0.14,<0.15
      - spherical_geometry >= 1.4.0,<1.5
      - stsci.imagestats >=1.8.3,<1.9
      - stcal >=1.17.0,<1.18
      - stpipe >=0.11.0,<0.12.0
